# Generated by Django 4.2.13 on 2024-06-28 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_claimed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
